# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rpq0uipsXpYIgpqr4TRWDvPHhNhHeSrA
"""

from flask import Flask, request, jsonify
from models import db, Customer, Order
from config import Config
from auth import require_oauth
import africastalking

app = Flask(__name__)
app.config.from_object(Config)
db.init_app(app)

# Africa's Talking SMS configuration
africastalking.initialize(Config.AFRICASTALKING_USERNAME, Config.AFRICASTALKING_API_KEY)
sms = africastalking.SMS

@app.route('/customers', methods=['POST'])
@require_oauth
def add_customer():
    data = request.json
    new_customer = Customer(name=data['name'], code=data['code'])
    db.session.add(new_customer)
    db.session.commit()
    return jsonify({"message": "Customer added"}), 201

@app.route('/orders', methods=['POST'])
@require_oauth
def add_order():
    data = request.json
    customer = Customer.query.filter_by(id=data['customer_id']).first()
    if not customer:
        return jsonify({"message": "Customer not found"}), 404

    new_order = Order(item=data['item'], amount=data['amount'], customer_id=customer.id)
    db.session.add(new_order)
    db.session.commit()

    # Send SMS via Africa's Talking
    response = sms.send(f"Order for {new_order.item} received", [customer.phone])

    return jsonify({"message": "Order added, SMS sent"}), 201

if __name__ == '__main__':
    app.run(debug=True)