# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rpq0uipsXpYIgpqr4TRWDvPHhNhHeSrA
"""

class Config:
    SQLALCHEMY_DATABASE_URI = 'sqlite:///customer_order.db'
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SECRET_KEY = 'your_secret_key'

    # Africa's Talking Config
    AFRICASTALKING_USERNAME = 'your_username'
    AFRICASTALKING_API_KEY = 'your_api_key'