# -*- coding: utf-8 -*-
"""test_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rpq0uipsXpYIgpqr4TRWDvPHhNhHeSrA
"""

import pytest
from app import app, db

@pytest.fixture
def client():
    app.config['TESTING'] = True
    with app.test_client() as client:
        with app.app_context():
            db.create_all()
        yield client

def test_add_customer(client):
    response = client.post('/customers', json={'name': 'Test Customer', 'code': 'CUST001'})
    assert response.status_code == 201

def test_add_order(client):
    response = client.post('/orders', json={'item': 'Test Item', 'amount': 100, 'customer_id': 1})
    assert response.status_code == 201